import type { ServiceDetailData } from "@/types/services"

export const digitalServiceCopy: Record<
  string,
  Omit<ServiceDetailData, "name"> & { shortTitle: string }
> = {
  "performance-marketing": {
    shortTitle: "Performance Marketing",
    title: "You Don't Have an Ad Problem. You Have a Math Problem.",
    description: "Clicks are cheap. Customers are not. Our performance marketing team runs Google, Meta, YouTube and LinkedIn ads around the only numbers that matter: what each lead costs, what each customer costs, and what comes back for every rupee you spend.",
    whatIs: "Why most ad budgets leak We audit a lot of ad accounts. The same problems show up again and again: conversion tracking that counts page views as leads, broad campaigns showing ads to people who will never buy, one tired creative running for months, and nobody calling the leads back within the hour. The platform keeps spending. The business keeps wondering why sales have not moved. Performance marketing fixes the math, not just the ads.",
    approach: [
      { title: "Unit economics", description: "We work out what a customer is worth to you and what you can afford to pay for one. That number sets every bid and budget." },
      { title: "Build and launch", description: "Campaign structure, audiences, ad copy, creatives and landing pages built to match each stage of intent." },
      { title: "Test and scale", description: "Structured A/B tests on creative, offer and audience every week. Budget moves to the winners. Losers are paused fast." },
      { title: "Close the loop", description: "We connect ad data to your CRM or sales sheet so we can see which campaigns bring paying customers, then optimise for those." },
    ],
    deliverables: [
      "Google Ads (Search, Performance Max, Display, YouTube)",
      "Meta Ads (Facebook and Instagram)",
      "LinkedIn Ads",
      "WhatsApp-led campaigns",
      "Tracking and attribution",
    ],
    effectiveFor: [
      "Clinics, hospitals and diagnostics centres that need patient enquiries.",
      "Restaurants, cafes and cloud kitchens driving reservations and direct orders.",
      "Real estate developers and furniture brands generating site visits and showroom walk-ins.",
      "Colleges and edtech running admission seasons.",
      "D2C and e-commerce brands focused on ROAS.",
      "B2B and SaaS companies chasing qualified demos.",
    ],
    faqs: [
      { question: "What is the minimum ad budget you recommend?", answer: "For local lead generation in Hyderabad or Bangalore, most businesses need enough budget to get at least 30 to 50 conversions a month so the platforms can optimise. We suggest a starting budget after the audit, based on your industry's typical cost per lead." },
      { question: "Google Ads or Meta Ads: which is better for my business?", answer: "Google Ads captures people already searching for your service, so it suits high-intent needs like clinics, repairs and B2B. Meta Ads creates demand through visuals and targeting, so it suits food, fashion, beauty, real estate and events. Most growing businesses use both, with budget shifted by results." },
      { question: "How fast will performance marketing show results?", answer: "Leads usually start within the first week. The first two to four weeks are a learning phase where we test audiences and creatives. Cost per lead typically stabilises and improves from the second month onwards." },
    ],
  },
  "growth-marketing": {
    shortTitle: "Growth Marketing",
    title: "Growth Isn't a Campaign. It's a Habit of Testing.",
    description: "Performance marketing buys you customers. Growth marketing makes every customer cheaper to win, more likely to buy again and more likely to bring a friend. We run the experiments that move your whole funnel, not just the top of it.",
    whatIs: "When more ad spend stops working Every scaling brand hits the same wall. Ad costs climb, conversion rates flatten, and the only lever left seems to be \"spend more\". The problem is rarely the ads. It is the landing page that loses 70% of visitors, the onboarding that confuses, the customers who buy once and disappear. Growth marketing fixes the leaks between the ad and the repeat purchase.",
    approach: [
      { title: "Diagnose", description: "Funnel data, customer interviews and competitor review show where growth is stuck." },
      { title: "Hypothesise and prioritise", description: "Each idea becomes a testable hypothesis with an expected impact. We pick the best few for each sprint." },
      { title: "Test, learn, scale", description: "Two to four week sprints. Winners are rolled out. Learnings are documented. Then we go again." },
    ],
    deliverables: [
      "Conversion rate optimisation (CRO)",
      "Experiment roadmap",
      "Retention and lifecycle",
      "Referral and loyalty loops",
      "Pricing and offer testing",
    ],
    effectiveFor: [
      "Funded startups in Bangalore and Hyderabad that need efficient, repeatable growth.",
      "D2C and e-commerce brands with healthy traffic but weak conversion or repeat rates.",
      "SaaS companies improving trial-to-paid conversion.",
      "Service businesses with high lead volume but low closing rates.",
    ],
    faqs: [
      { question: "What is the difference between growth marketing and performance marketing?", answer: "Performance marketing focuses on acquiring customers through paid ads at a target cost. Growth marketing covers the entire funnel, including conversion, retention, referrals and pricing, and uses continuous experiments to make each customer more valuable and cheaper to acquire. Digi Carotene often runs both together." },
      { question: "How many experiments do you run each month?", answer: "It depends on your traffic and team capacity. Most clients run four to eight meaningful experiments a month. Low-traffic sites run fewer, larger tests so results are statistically reliable rather than random." },
      { question: "Is growth marketing only for startups?", answer: "No. Any business with an existing flow of visitors or leads can benefit. Restaurants improving repeat orders, clinics improving appointment show-up rates and colleges improving application completion are all growth marketing problems." },
    ],
  },
  "seo": {
    shortTitle: "Search Engine Optimization",
    title: "Ranking #1 Isn't the Finish Line Anymore. Being the Answer Is.",
    description: "Your customers are still searching on Google. But more and more, they are also asking ChatGPT, Gemini, Perplexity and Google's AI Overviews, and getting one answer back. We make sure that answer is you.",
    whatIs: "Search changed. Most SEO didn't. In 2026, Google shows AI-generated answers above the regular results for a large share of searches, and a randomized study published this year found those AI Overviews cut clicks to websites by roughly 40%. Meanwhile India has around 100 million weekly ChatGPT users asking it everything from \"best skin clinic in Jubilee Hills\" to \"which CRM should a 50-person company use\". Old-school SEO, which means stuffing keywords and buying links, does not get you into those answers. Clear, trusted, well-structured information does. That is what we build.",
    approach: [
      { title: "Strategy and roadmap", description: "A 90-day plan prioritised by impact: quick technical wins first, then high-intent pages, then authority." },
      { title: "Fix and build", description: "Our developers and writers implement the changes. We do not hand you a 60-page PDF and leave." },
      { title: "Measure and expand", description: "Monthly tracking of rankings, organic leads, Google Business Profile actions and AI citation share. Then we expand into the next keyword cluster." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "How do I get my business recommended by ChatGPT?", answer: "AI tools recommend brands they see described consistently across trusted sources. Make sure your website clearly states who you are, what you do and where; keep your details identical on Google Business Profile, LinkedIn and directories; earn reviews and press mentions; and publish answer-first content to the questions customers ask." },
      { question: "Do I still need SEO if people use AI search?", answer: "Yes. AI answer engines mostly draw on pages that already rank well and are trusted. Strong SEO is the foundation; AEO and GEO build on it so you appear both in the regular results and in the AI-generated answer." },
      { question: "How much do SEO services cost in Hyderabad?", answer: "SEO pricing depends on the number of locations, pages, competition and whether content and development are included. Digi Carotene offers monthly retainers with a fixed scope agreed after a free audit, with clear deliverables and the metrics we will report against." },
      { question: "What is local SEO?", answer: "Local SEO helps your business appear in Google Maps and \"near me\" results in a specific area. It includes optimising your Google Business Profile, building reviews, keeping your name, address and phone consistent across listings, and creating location-specific pages." },
    ],
  },
  "content": {
    shortTitle: "Content Marketing",
    title: "Nobody Wakes Up Wanting to Read Your Brochure.",
    description: "They wake up with a question. \"Is laser hair removal safe?\" \"Which school board is better for my child?\" \"How do I choose an ERP?\" Content marketing is how you become the brand that answers it, on Google, in AI search and on social, before your competitor does.",
    whatIs: "Content that answers beats content that announces Most brand content talks about the brand: our launch, our award, our team outing. Customers care about their problem. AI answer engines care about clear, trustworthy answers. Content that leads with real questions earns rankings, citations, shares and, eventually, sales.",
    approach: [
      { title: "Plan", description: "A content calendar mapped to the funnel: awareness, consideration and decision content in the right balance." },
      { title: "Create", description: "Written by specialists, reviewed by subject experts on your team where accuracy matters, especially in healthcare, finance and education." },
      { title: "Distribute and measure", description: "Every piece is tracked for rankings, AI citations, engagement and the leads it influences." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Do you use AI to write content?", answer: "We use AI for research and drafting support, but every piece is planned, written and edited by experienced writers and fact-checked. Google and AI engines reward content that shows real expertise, so human judgement stays at the centre." },
      { question: "What kind of content gets cited by AI search engines?", answer: "Content that directly answers a specific question in the first few lines, uses clear headings, includes facts with sources, and comes from a brand that is consistently described across the web. FAQ sections, comparison tables and definitions are especially likely to be quoted." },
    ],
  },
  "social": {
    shortTitle: "Social Media Marketing",
    title: "Followers Don't Pay Rent. Customers Do.",
    description: "We build social media that people stop for, save, share and act on. Reels with hooks that hold, content calendars rooted in data, communities that reply, and paid social that turns attention into enquiries.",
    whatIs: "Posting every day isn't a strategy Many brands post daily and still struggle to get a single enquiry from Instagram. The reason is simple: the content is made for the brand, not for the audience. Platforms reward what people watch to the end, save and send to a friend. That takes research, sharp hooks and constant testing, not just a calendar full of festival greetings.",
    approach: [
      { title: "Strategy", description: "Pillars, formats, posting rhythm and the KPIs we will be judged on." },
      { title: "Create and publish", description: "Monthly calendar, shoots, edits, captions and scheduling." },
      { title: "Learn and adapt", description: "Monthly analysis of what drove saves, shares and enquiries, then we double down on winners." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "How many posts per month do you create?", answer: "Packages typically include 12 to 30 pieces a month, with a mix of reels, carousels, stories and statics. We recommend fewer, better posts with strong reels over high-volume, low-impact posting." },
      { question: "Can social media actually generate leads?", answer: "Yes, when it is built for it. Clear calls to action, link-in-bio landing pages, click-to-WhatsApp ads, lead forms and fast DM replies turn engagement into enquiries. We track every lead source so you can see what social contributes." },
    ],
  },
  "graphic-design": {
    shortTitle: "Graphic Designing",
    title: "Before Anyone Reads a Word, They've Already Judged the Design.",
    description: "Design is the first impression your brand makes on a feed, a shelf, a hoarding or a website. We design work that looks good and does a job: gets noticed, builds trust and gets people to act.",
    whatIs: "Pretty isn't the brief. Performance is. A beautiful design that nobody remembers is a cost. A clear, consistent design system that makes every ad and post instantly recognisable is an asset. We design with performance data in mind, including which creatives get clicked, which packaging gets picked up and which layouts convert, and we test ad creatives the way we test headlines.",
    approach: [
      { title: "Concepts", description: "Two to three distinct directions with the reasoning behind each." },
      { title: "Refine", description: "Focused revisions on the chosen direction." },
      { title: "Deliver and systemise", description: "Final files in every format you need, plus templates so your brand stays consistent." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Do I get the source files?", answer: "Yes. Once the project is complete and paid for, you receive the final source files and full usage rights to the approved designs." },
      { question: "Can you design ads that perform better?", answer: "Yes. We design multiple variations per campaign, testing hooks, visuals, offers and formats, and use the results from your ad accounts to guide the next round. Design decisions are backed by click and conversion data." },
    ],
  },
  "web": {
    shortTitle: "Web Design and Development",
    title: "Your Website Is Either Your Best Salesperson or the Reason Leads Quietly Leave.",
    description: "Most visitors decide within seconds whether to stay. We design and build websites that load fast, explain clearly, rank on Google, get read by AI and turn visitors into enquiries.",
    whatIs: "A beautiful website that doesn't convert is an expensive brochure We see it all the time: a stunning homepage, a contact form buried three clicks deep, a mobile version that takes eight seconds to load and service pages that never say what the business actually does. Every ad rupee and SEO effort you make ends up on your website. If the site leaks, everything leaks.",
    approach: [
      { title: "Structure and content", description: "Sitemap, wireframes and conversion-focused copy before any visuals." },
      { title: "Design", description: "Brand-aligned visual design for mobile and desktop." },
      { title: "Build and test", description: "Development, speed optimisation, cross-device testing and SEO checks." },
      { title: "Launch and improve", description: "Go-live, redirects, tracking checks and post-launch conversion improvements." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Will my website be SEO-friendly?", answer: "Yes. Every Digi Carotene website includes technical SEO setup, including fast load times, mobile optimisation, unique meta tags, schema markup and a clean structure, plus AEO-ready content blocks so search engines and AI assistants can understand and quote your pages." },
      { question: "Which platform do you build on?", answer: "We recommend the platform based on your needs: WordPress for content-rich sites you want to manage yourself, Shopify for e-commerce, and Next.js or custom builds for high-performance or application-style websites." },
      { question: "Do you offer website maintenance?", answer: "Yes. We offer monthly maintenance covering security updates, backups, uptime monitoring, speed checks and small content changes." },
    ],
  },
  "personal-branding": {
    shortTitle: "Personal Branding",
    title: "People Buy From People. Especially the One at the Top.",
    description: "Before a client signs, an investor commits or a candidate joins, they look you up. They check your LinkedIn, your Instagram, what the press says and, increasingly, what ChatGPT says about you. We make sure what they find builds trust.",
    whatIs: "Your reputation is already online. The question is who's writing it. Founders, doctors, consultants and executives are often the most trusted asset a business has, and the least visible one. A thoughtful LinkedIn presence, a few strong media mentions and a clear story can open doors that ad budgets never will. Done badly, it reads as self-promotion. Done well, it reads as expertise.",
    approach: [
      { title: "Interviews", description: "Two to three recorded conversations to capture your voice, opinions and stories." },
      { title: "Content engine", description: "A monthly calendar of posts and videos you approve in minutes, not hours." },
      { title: "Amplify", description: "PR, speaking opportunities and collaborations that multiply reach." },
    ],
    deliverables: [
      "LinkedIn growth",
      "Instagram and video presence",
      "Thought leadership and PR",
      "Search and AI reputation",
    ],
    effectiveFor: [
      "Startup founders in Bangalore and Hyderabad building credibility with investors, talent and customers.",
      "Doctors and healthcare professionals building patient trust.",
      "Consultants, lawyers and chartered accountants growing referrals.",
      "CXOs and senior leaders preparing for their next chapter.",
      "Creators, stylists and coaches turning expertise into a business.",
    ],
    faqs: [
      { question: "How long does it take to build a personal brand on LinkedIn?", answer: "Most people see noticeably better engagement and inbound conversations within 8 to 12 weeks of consistent posting. Building recognised authority in your industry usually takes 6 to 12 months." },
      { question: "Is personal branding only for big founders?", answer: "Not at all. Doctors, consultants, small business owners and mid-career professionals often benefit the most, because a strong personal brand directly brings them clients, referrals and opportunities." },
    ],
  },
  "email": {
    shortTitle: "Email and WhatsApp Marketing",
    title: "The Cheapest Customer Is the One Who Already Said Yes Once.",
    description: "Winning a new customer costs far more than bringing back an existing one. Yet most brands spend almost everything on acquisition and almost nothing on the people already in their database. We build automated email and WhatsApp journeys that turn one-time buyers into regulars.",
    whatIs: "Your database is your most under-used asset Every past customer, enquiry, cart and walk-in phone number is a relationship waiting for the right message at the right time. Sent badly, messages get ignored or blocked. Sent well (personal, timely and useful), they become your highest-return channel.",
    approach: [
      { title: "Map the journeys", description: "The moments in your customer lifecycle where a message can change behaviour." },
      { title: "Build and write", description: "Templates, copy, design and automation logic." },
      { title: "Measure and refine", description: "Open, click, reply, booking and revenue tracking per journey, improved every month." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants and cloud kitchens driving repeat orders.",
      "Clinics, salons and wellness brands reducing no-shows and driving rebookings.",
      "E-commerce and D2C brands recovering carts and growing repeat purchases.",
      "Schools and colleges nurturing admission enquiries.",
      "B2B companies nurturing long sales cycles.",
    ],
    faqs: [
      { question: "Is email marketing still effective in India?", answer: "Yes, especially for B2B, education, e-commerce and content-led brands. Email is ideal for detailed information, newsletters and long nurture sequences, while WhatsApp suits quick, transactional and time-sensitive messages. Most brands get the best results using both." },
      { question: "How much does WhatsApp Business API cost?", answer: "WhatsApp charges per message based on the message category (marketing, utility or authentication) and country, in addition to any platform provider fees. We help you estimate costs based on your volumes before setup." },
    ],
  },
  "insta-shoot": {
    shortTitle: "Insta Shoot",
    title: "The Algorithm Rewards Content That Looks Like It Belongs in the Feed.",
    description: "Not polished TV ads. Not stock photos. Real, scroll-stopping reels and photos of your food, your space, your product and your people, planned, shot and edited by a team that understands both cameras and conversion.",
    whatIs: "Great content is planned before the camera is switched on The difference between a reel that gets 500 views and one that gets 50,000 is rarely the camera. It is the hook in the first two seconds, the pacing, the on-screen text and whether it feels native to the platform. Our shoots start with scripts and shot lists built from what is actually performing in your category.",
    approach: [
      { title: "Pre-production call", description: "We agree on goals, concepts, scripts, location, talent and props." },
      { title: "Shoot day", description: "A focused half-day or full-day session to capture a month's worth of content in one go." },
      { title: "Edit and review", description: "First cuts within [[turnaround days — to confirm]], with one round of revisions included." },
      { title: "Publish and learn", description: "Content goes into your calendar, and performance data shapes the next shoot." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Do I need to provide models or talent?", answer: "Not necessarily. Many of the best-performing reels feature founders, staff or real customers. If you need models, anchors or creators, we can source and manage them for you." },
      { question: "Do you also post the content?", answer: "Yes. Shoots can be booked on their own or bundled with our social media management, where we plan, publish and track the content's performance." },
    ],
  },
}
