import type { ServiceDetailData } from "@/types/services"

export const offlineServiceCopy: Record<
  string,
  Omit<ServiceDetailData, "name"> & { shortTitle: string }
> = {
  "mall-activations": {
    shortTitle: "Mall Activations",
    title: "Weekend Mall Crowds Aren't Just Browsing. They're in a Buying Mood.",
    description: "Families with time, couples with plans and shoppers with wallets already open. A mall activation puts your brand in front of thousands of people at the exact moment they are looking for something new to try. We design, build and run activations that get people to stop, try and sign up.",
    whatIs: "Footfall is easy. Engagement is the job. Thousands of people walk past a mall kiosk every weekend. Most kiosks get ignored because they look like every other stall and ask for too much too soon. Ours are built around one simple hook (a game, a free trial, a photo moment, an instant offer) and a two-tap way to stay in touch.",
    approach: [
      { title: "Plan", description: "Booth concept, engagement mechanic, staffing plan and tracking setup." },
      { title: "Build", description: "Fabrication, branding, tech setup and promoter training." },
      { title: "Run and refine", description: "Live execution with daily reporting and on-the-spot tweaks to what works." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Do you handle mall permissions?", answer: "Yes. We manage slot bookings, mall approvals, insurance and fabrication guidelines, and coordinate directly with mall marketing teams so you do not have to." },
      { question: "How long does a mall activation usually run?", answer: "Most mall activations run over a weekend (two to three days) or across consecutive weekends. Lead generation booths for real estate or education often run two to four weeks for consistent volume." },
      { question: "How much does a mall activation cost?", answer: "Costs depend on the mall, location within the mall, duration, booth size, fabrication and staffing. After understanding your goals, we share options at different budgets with expected engagement and lead estimates." },
    ],
  },
  "residential-activations": {
    shortTitle: "Residential Activations",
    title: "Hundreds of Households. One Gate. Zero Ad Clutter.",
    description: "Large gated communities in Hyderabad and Bangalore are towns in their own right, with families, decision-makers and a clubhouse calendar. A well-run society activation puts your brand in front of the people who buy groceries, book clinics, choose schools and renovate homes, in the one place they trust most.",
    whatIs: "The most trusted media in India is a neighbour's recommendation In a gated community, word travels fast. One good experience at the weekend stall becomes a WhatsApp group recommendation by Monday. That is why residential activations work so well for local services, home brands, healthcare, education and food: they combine direct reach with built-in word of mouth.",
    approach: [
      { title: "Secure", description: "Permissions, dates and slots aligned with weekends and community events." },
      { title: "Execute", description: "Setup, engagement and lead capture with daily reporting." },
      { title: "Follow up", description: "WhatsApp and call follow-ups within 24 hours, when interest is highest." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Do you get permission from the society?", answer: "Yes. All residential activations are run with written approval from the residents' welfare association or facility management. We never run unauthorised door-to-door campaigns." },
      { question: "How many societies should I cover?", answer: "For a local service, three to five well-matched societies near your location over a month usually gives a clear read on response. Larger brands often run rolling programmes across 20 or more communities." },
    ],
  },
  "theatre-marketing": {
    shortTitle: "Theatre Marketing",
    title: "A Dark Room, a Giant Screen and No Skip Button.",
    description: "Cinema is one of the few places left where an audience sits still, looks forward and pays full attention. In Hyderabad, where movies are close to a religion, and in Bangalore's packed multiplexes, theatre marketing gives your brand a big-screen moment that no feed can match.",
    whatIs: "Attention is the scarcest thing in marketing On a phone, your ad competes with a hundred notifications and a thumb ready to scroll. In a cinema, it is the biggest thing in the room. That is why cinema works so well for launches, real estate, automotive, local retail and any brand that wants to look bigger than its budget.",
    approach: [
      { title: "Create", description: "Produce or adapt your ad film for the big screen, with a clear call to action and QR." },
      { title: "Book and run", description: "Media buying with cinema partners, plus lobby activation logistics if required." },
      { title: "Measure", description: "Screening confirmations, QR scans, offer redemptions and footfall uplift near the cinema." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Can I choose which movies my ad plays with?", answer: "In many cases, yes. You can target by language and often by specific films or genres, which is useful for aligning with big releases or audiences such as families, youth or premium viewers." },
      { question: "How long should a cinema ad be?", answer: "Most cinema ads run 10, 20 or 30 seconds. Shorter spots suit reminder and offer messages, while 30 to 60 seconds suits launches and storytelling. We recommend length based on your goal and budget." },
    ],
  },
  "campus-activations": {
    shortTitle: "Campus Activations",
    title: "Gen Z Can Spot an Ad From a Mile Away. So Don't Bring One. Bring an Experience.",
    description: "Students do not respond to banners. They respond to brands that show up with something fun, useful or worth sharing. We create campus activations that students actually join, talk about and post, and we connect every interaction to your app, store or CRM.",
    whatIs: "Win them early, win them for years The choices students make today, including their first phone plan, first bank account, favourite food app and go-to clothing brand, often stick for a decade. Hyderabad and Bangalore are two of India's biggest student hubs, with engineering, management, design, medical and arts colleges packed with digital-first young adults. Campus is where brand loyalty starts.",
    approach: [
      { title: "Design the hook", description: "An experience students want to join and share, not a pamphlet." },
      { title: "Activate", description: "Permissions, setup, ambassadors and on-ground execution." },
      { title: "Track and extend", description: "Referral codes, app installs, QR sign-ups, social reach and retargeting." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "When is the best time for campus activations?", answer: "Fest season, orientation weeks and the weeks before exams start are the best windows. We avoid exam periods and holidays. Most college fests in Hyderabad and Bangalore cluster between January and April and again around August to October." },
      { question: "How do you measure campus campaign results?", answer: "Through unique referral codes, app installs, QR sign-ups, ambassador leaderboards, social content reach and sales from campus-specific offers, all reported by college." },
    ],
  },
  "corporate-events": {
    shortTitle: "Corporate Events",
    title: "An Event Is Over in a Day. The Right One Pays Off for a Year.",
    description: "A launch that gets press. A conference that fills your pipeline. A dealer meet that sets the sales tone for the year. A town hall your people actually remember. We plan and produce corporate events with one extra thing most event companies forget: what happens after.",
    whatIs: "Most events end when the lights go off. Ours don't. Big budgets are often spent on stage, sound and catering, while the content, follow-up and PR that create lasting value are an afterthought. Because we are a marketing agency first, every event we run comes with a content plan, a lead capture plan and a post-event amplification plan.",
    approach: [
      { title: "Concept and plan", description: "Theme, venue, budget, run-of-show and marketing plan." },
      { title: "Produce", description: "Fabrication, AV, talent, vendors, guest management and rehearsals." },
      { title: "Execute", description: "On-ground team managing every detail on the day." },
      { title: "Amplify", description: "Same-day content, press releases, follow-up campaigns and a results report." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Do you handle event marketing and registrations?", answer: "Yes. We manage event websites, registration pages, email and WhatsApp invites, paid promotion, attendee communication and post-event follow-ups, along with on-ground production." },
      { question: "Can you cover the event with photos and videos?", answer: "Yes. Our in-house production team covers events with photography, video, live reels and highlight films, so you have content for social media, PR and internal communications." },
    ],
  },
  "festival-marketing": {
    shortTitle: "Festival Marketing",
    title: "In Hyderabad and Bengaluru, the Calendar Is the Media Plan.",
    description: "From Sankranti kites to Bathukamma flowers, Ugadi pachadi to Dasara lights, festivals are when families shop, gift, celebrate and spend the most. They are also when every brand shouts at once. We help you show up with meaning, not noise.",
    whatIs: "Every brand posts \"Happy Diwali\". Few are remembered for it. Festive season is the busiest and most expensive time to advertise. Generic greetings get lost. What works is cultural understanding, an offer that fits the moment and a presence where celebrations actually happen: in pandals, society events, markets and family WhatsApp groups.",
    approach: [
      { title: "Idea", description: "One strong, culturally relevant idea per festival, not a greeting template." },
      { title: "Activate", description: "On-ground presence, creatives, influencers and ads launched in sync." },
      { title: "Measure", description: "Sales, footfall, redemptions and engagement compared with previous festive seasons." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "How do you avoid culturally insensitive campaigns?", answer: "Our team is rooted in Hyderabad and Bangalore. We research each festival's traditions, run creatives past native-language reviewers and avoid using sacred symbols casually. When in doubt, we choose respect over shock value." },
      { question: "Can small businesses benefit from festival marketing?", answer: "Yes. Local festivals are ideal for small businesses, with society stalls, neighbourhood pandal sponsorships, WhatsApp offers and hyper-local ads delivering strong returns on modest budgets." },
    ],
  },
  "popup-stores": {
    shortTitle: "Popup Stores",
    title: "Scarcity Sells. A Store That Disappears on Sunday Sells Faster.",
    description: "A pop-up store gives online brands a physical home, gives established brands a fresh stage, and gives customers a reason to come now. We find the location, design the space, build it, staff it and measure it.",
    whatIs: "The cheapest way to test a city before you commit Signing a long retail lease without knowing if a neighbourhood will buy is a big bet. A pop-up lets you test demand, pricing and product mix in Hyderabad or Bangalore for weeks instead of years, while building buzz, content and a customer list.",
    approach: [
      { title: "Design", description: "A space people want to walk into and photograph." },
      { title: "Build and launch", description: "Fabrication, setup, launch event and promotion." },
      { title: "Operate and learn", description: "Daily sales tracking and a clear go or no-go recommendation on permanent retail." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "How much does a pop-up store cost?", answer: "Costs depend on location rent, size, duration, fabrication and staffing. Modular builds keep costs down and can be reused across cities. We share options at different budgets after understanding your goals." },
      { question: "Is a pop-up worth it for a D2C brand?", answer: "Often, yes. Pop-ups let customers touch and try products, which builds trust that is hard to create online. They also generate content, reviews and a customer list for future online marketing." },
    ],
  },
  "influencer-campaigns": {
    shortTitle: "Influencer Campaigns",
    title: "Your Audience Already Trusts Someone. Let's Make Sure They're Talking About You.",
    description: "People trust creators they follow far more than they trust ads. We match your brand with the right Hyderabad and Bangalore creators, from food bloggers to tech reviewers, brief them properly, bring them to your events and measure what they actually deliver.",
    whatIs: "Followers are a vanity metric. Fit is everything. A creator with 2 million followers across India may do less for your Gachibowli restaurant than five local food creators with 40,000 followers each. India's influencer marketing industry is now worth several thousand crore rupees and growing over 20% a year, which means more noise, more fake followers and more wasted budgets. We pick creators on audience location, engagement quality and past results, not follower count.",
    approach: [
      { title: "Match", description: "A shortlist of creators with audience data for your approval." },
      { title: "Create", description: "Briefs, content reviews and coordinated posting schedules." },
      { title: "Measure", description: "Results per creator, so the next campaign only uses the ones who delivered." },
    ],
    deliverables: [
      "Briefs and negotiation",
      "Event and store visits",
      "Content rights and whitelisting",
      "Tracking and reporting",
      "Compliance",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Are micro-influencers better than big influencers?", answer: "For local businesses and niche products, often yes. Micro-influencers (roughly 10,000 to 100,000 followers) usually have more engaged, local audiences and lower costs. Larger creators suit mass awareness and big launches." },
      { question: "Do influencer posts need to be disclosed?", answer: "Yes. In India, ASCI guidelines require paid or gifted collaborations to be clearly disclosed with labels like #ad, #collab or #sponsored. We ensure every campaign follows these rules." },
    ],
  },
  "metro-branding": {
    shortTitle: "Metro Branding",
    title: "Lakhs of Commuters. Same Route. Every Single Day.",
    description: "Repetition is what builds recall, and the metro delivers it like nothing else. The same professionals, students and families pass the same stations twice a day, five days a week. Metro branding turns that daily habit into brand familiarity.",
    whatIs: "The commute is the one ad slot people can't skip Hyderabad Metro carries around 4.5 lakh passengers a day across 69 km, with Ameerpet, Miyapur, Raidurg and HITEC City among its busiest stations. Bengaluru's Namma Metro, India's second-largest network at about 96 km and 83 stations, averaged over 9 lakh riders a day in early 2026 and has crossed 10 lakh on peak days. That is a captive, largely urban, working-age audience, many of them right in the IT corridors where purchasing power is highest.",
    approach: [
      { title: "Creative", description: "Designs built for a three-second glance, with a clear message and QR where it works." },
      { title: "Media buying", description: "Negotiation and booking through authorised concessionaires on both networks." },
      { title: "Monitoring", description: "Installation proofs, periodic checks, QR scan tracking and footfall uplift measurement." },
    ],
    deliverables: [
      "Strategy and campaign plan",
      "Creative and production",
      "Tracking and reporting",
      "Weekly optimisation",
    ],
    effectiveFor: [
      "Restaurants, cafes and QSR",
      "Healthcare and wellness",
      "Education",
      "Real estate and home",
      "Retail and local services",
      "Technology and B2B",
    ],
    faqs: [
      { question: "Which metro stations are best for advertising?", answer: "For Hyderabad, high-traffic interchanges and IT corridor stations such as Ameerpet, Raidurg, HITEC City and Miyapur deliver the most footfall. In Bangalore, Majestic and stations along the Purple Line and Yellow Line serving Whitefield and Electronic City are popular. The best choice depends on where your audience lives and works." },
      { question: "How long should a metro campaign run?", answer: "Most metro campaigns run for at least one to three months to build recall through repeated exposure. Short, high-impact bursts of two to four weeks work for launches and festive offers." },
    ],
  },
}
