/** Field options from Growth-Audit-Popup-Form-Spec.pdf */

export const AUDIT_REPLY_DAYS = "2 working days"

export const auditIndustries = [
  "Healthcare & Clinics",
  "Restaurants, Cafés & QSR",
  "Salons & Beauty",
  "Education & Coaching",
  "Real Estate & Furniture",
  "D2C, Food & Retail",
  "B2B & Technology",
  "Fashion & Lifestyle",
  "Events & Entertainment",
  "Other",
] as const

export const adsRunningOptions = [
  "Meta (Facebook/Instagram)",
  "Google",
  "YouTube",
  "LinkedIn",
  "Not running ads",
] as const

export const ADS_NOT_RUNNING = "Not running ads" as const

export const auditGoals = [
  "More leads & enquiries",
  "More online sales",
  "Lower ad costs",
  "More walk-ins / footfall",
  "Brand awareness",
  "Something else",
] as const

export const budgetRangesInr = [
  "₹25,000–50,000",
  "₹50,000–1 lakh",
  "₹1–3 lakh",
  "₹3 lakh+",
  "Not sure yet",
] as const

export const budgetRangesUsd = [
  "Under $500",
  "$500–1,000",
  "$1,000–3,000",
  "$3,000–10,000",
  "$10,000+",
  "Not sure yet",
] as const

/** Dial codes used in the phone field (India default). */
export const countryDialCodes = [
  { code: "+91", country: "India", iso: "IN" },
  { code: "+1", country: "United States", iso: "US" },
  { code: "+44", country: "United Kingdom", iso: "GB" },
  { code: "+971", country: "United Arab Emirates", iso: "AE" },
  { code: "+65", country: "Singapore", iso: "SG" },
  { code: "+61", country: "Australia", iso: "AU" },
  { code: "+49", country: "Germany", iso: "DE" },
  { code: "+33", country: "France", iso: "FR" },
  { code: "+966", country: "Saudi Arabia", iso: "SA" },
  { code: "+974", country: "Qatar", iso: "QA" },
  { code: "+965", country: "Kuwait", iso: "KW" },
  { code: "+968", country: "Oman", iso: "OM" },
  { code: "+973", country: "Bahrain", iso: "BH" },
  { code: "+92", country: "Pakistan", iso: "PK" },
  { code: "+880", country: "Bangladesh", iso: "BD" },
  { code: "+94", country: "Sri Lanka", iso: "LK" },
  { code: "+977", country: "Nepal", iso: "NP" },
  { code: "+60", country: "Malaysia", iso: "MY" },
  { code: "+62", country: "Indonesia", iso: "ID" },
  { code: "+63", country: "Philippines", iso: "PH" },
  { code: "+66", country: "Thailand", iso: "TH" },
  { code: "+81", country: "Japan", iso: "JP" },
  { code: "+82", country: "South Korea", iso: "KR" },
  { code: "+86", country: "China", iso: "CN" },
  { code: "+852", country: "Hong Kong", iso: "HK" },
  { code: "+27", country: "South Africa", iso: "ZA" },
  { code: "+234", country: "Nigeria", iso: "NG" },
  { code: "+254", country: "Kenya", iso: "KE" },
  { code: "+55", country: "Brazil", iso: "BR" },
  { code: "+52", country: "Mexico", iso: "MX" },
  { code: "+64", country: "New Zealand", iso: "NZ" },
  { code: "+353", country: "Ireland", iso: "IE" },
  { code: "+31", country: "Netherlands", iso: "NL" },
  { code: "+41", country: "Switzerland", iso: "CH" },
  { code: "+46", country: "Sweden", iso: "SE" },
  { code: "+47", country: "Norway", iso: "NO" },
  { code: "+45", country: "Denmark", iso: "DK" },
  { code: "+39", country: "Italy", iso: "IT" },
  { code: "+34", country: "Spain", iso: "ES" },
  { code: "+351", country: "Portugal", iso: "PT" },
  { code: "+48", country: "Poland", iso: "PL" },
  { code: "+90", country: "Turkey", iso: "TR" },
  { code: "+7", country: "Russia", iso: "RU" },
  { code: "+380", country: "Ukraine", iso: "UA" },
  { code: "+20", country: "Egypt", iso: "EG" },
  { code: "+212", country: "Morocco", iso: "MA" },
  { code: "+233", country: "Ghana", iso: "GH" },
  { code: "+256", country: "Uganda", iso: "UG" },
  { code: "+255", country: "Tanzania", iso: "TZ" },
] as const

/** Full country list for the Country field (India default). */
export const auditCountries = [
  "India",
  "United States",
  "United Kingdom",
  "United Arab Emirates",
  "Singapore",
  "Australia",
  "Canada",
  "Germany",
  "France",
  "Saudi Arabia",
  "Qatar",
  "Kuwait",
  "Oman",
  "Bahrain",
  "Pakistan",
  "Bangladesh",
  "Sri Lanka",
  "Nepal",
  "Malaysia",
  "Indonesia",
  "Philippines",
  "Thailand",
  "Japan",
  "South Korea",
  "China",
  "Hong Kong",
  "Taiwan",
  "South Africa",
  "Nigeria",
  "Kenya",
  "Brazil",
  "Mexico",
  "New Zealand",
  "Ireland",
  "Netherlands",
  "Switzerland",
  "Sweden",
  "Norway",
  "Denmark",
  "Italy",
  "Spain",
  "Portugal",
  "Poland",
  "Turkey",
  "Russia",
  "Ukraine",
  "Egypt",
  "Morocco",
  "Ghana",
  "Uganda",
  "Tanzania",
  "Other",
] as const
